/*
 * Connexion PostgreSQL (base hébergée sur Coolify, réseau interne).
 * Remplace les modèles Odoo Studio x_game_release / x_game_score / x_game_save.
 *
 * - Pool unique, mis en cache sur globalThis (survit au hot-reload en dev).
 * - Le schéma est créé automatiquement au premier appel (idempotent).
 */
import { Pool, type QueryResultRow } from "pg";

const SCHEMA = `
CREATE TABLE IF NOT EXISTS game (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL,
  description text NOT NULL DEFAULT '',
  url         text NOT NULL,
  published   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS score (
  game_id    integer NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  user_id    integer NOT NULL,
  user_name  text NOT NULL DEFAULT '',
  score      bigint NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_id, user_id)
);

CREATE TABLE IF NOT EXISTS save (
  game_id    integer NOT NULL REFERENCES game(id) ON DELETE CASCADE,
  user_id    integer NOT NULL,
  data       jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (game_id, user_id)
);
`;

// Cache global : un seul pool et une seule création de schéma par process.
const g = globalThis as unknown as {
  _arcadePool?: Pool;
  _arcadeSchemaReady?: Promise<unknown>;
};

function getPool(): Pool {
  if (!g._arcadePool) {
    const url = process.env.DATABASE_URL;
    if (!url) {
      throw new Error("Configuration manquante : définir DATABASE_URL (voir .env.example).");
    }
    g._arcadePool = new Pool({ connectionString: url, max: 5 });
  }
  return g._arcadePool;
}

/** Exécute une requête SQL après s'être assuré que le schéma existe. */
export async function query<T extends QueryResultRow = any>(text: string, params?: unknown[]) {
  const pool = getPool();
  if (!g._arcadeSchemaReady) {
    g._arcadeSchemaReady = pool.query(SCHEMA).catch((e) => {
      // En cas d'échec, on retentera au prochain appel.
      g._arcadeSchemaReady = undefined;
      throw e;
    });
  }
  await g._arcadeSchemaReady;
  return pool.query<T>(text, params as any[]);
}
